### ISSUE TITLE
Remove local.properties from repository

### ISSUE THREAD

**Issue by mgasiorowski** [OWASP/OMTG-Hacking-Playground#2]
This file should not be checked into Version Control Systems ;)

Info from file:

>  This file must *NOT* be checked into Version Control Systems, as it contains information specific to your local configuration.

:)

**Comment by sushi2k** [comment]
True. Thx :-)
Fixed with https://github.com/OWASP/OMTG-Hacking-Playground/commit/54b0be02e07d0531553f67473a6c7c31cadb7de5
